TWEAK_NAME = IconSupport

IconSupport_OBJCC_FILES = IconSupport.mm IconSupportClassic.mm ISIconSupport.mm StaleFileAlert.mm Preferences.mm
IconSupport_FRAMEWORKS = UIKit CoreGraphics
IconSupport_OBJCCFLAGS = -include Headers.h -fvisibility=hidden

include ../theos/makefiles/common.mk
include ../theos/makefiles/tweak.mk
