TWEAK_NAME = IconSupport

IconSupport_OBJCC_FILES = Loader.xm
IconSupport_OBJCCFLAGS =  -include $(THEOS_PROJECT_DIR)/Libraries/Common/firmware.h -fvisibility=hidden

ARCHS ?= armv6 arm64

include $(THEOS)/makefiles/common.mk
include $(THEOS)/makefiles/tweak.mk
